# Generated by Django 4.0.3 on 2022-05-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule_post_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='post',
        ),
    ]
